# Generated by Django 3.2.5 on 2021-11-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
